version: '3'
services:
  app:
    user: '1000:1000'
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www/
    networks:
      - laravel
    depends_on:
      - db
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - app
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel
    ports:
      - "3306:3306"
networks:
  laravel:
    driver: bridge
