INSERT INTO `provinces` (`region_id`, `name`) VALUES ('1', 'Metro Manila');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('2', 'Ilocos Norte');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('2', 'Ilocos Sur');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('2', 'La Union');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('2', 'Pangasinan');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('3', 'Batanes');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('3', 'Cagayan');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('3', 'Isabela');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('3', 'Nueva Vizcaya');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('3', 'Quirino');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('4', 'Aurora');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('4', 'Bataan');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('4', 'Bulacan');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('4', 'Nueva Ecija');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('4', 'Pampanga');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('4', 'Tarlac');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('4', 'Zambales');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('5', 'Batangas');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('5', 'Cavite');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('5', 'Laguna');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('5', 'Quezon');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('5', 'Rizal');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('6', 'Marinduque');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('6', 'Occidental Mindoro');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('6', 'Oriental Mindoro');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('6', 'Palawan');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('6', 'Romblon');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('7', 'Albay');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('7', 'Camarines Norte');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('7', 'Camarines Sur');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('7', 'Catanduanes');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('7', 'Masbate');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('7', 'Sorsogon');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('8', 'Aklan');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('8', 'Antique');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('8', 'Capiz');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('8', 'Guimaras');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('8', 'Iloilo');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('8', 'Negros Occidental');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('9', 'Bohol');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('9', 'Cebu');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('9', 'Negros Oriental');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('9', 'Siquijor');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('10', 'Biliran');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('10', 'Eastern Samar');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('10', 'Leyte');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('10', 'Northern Samar');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('10', 'Samar');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('10', 'Southern Leyte');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('11', 'Zamboanga del Norte');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('11', 'Zamboanga del Sur');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('11', 'Zamboanga Sibugay');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('12', 'Bukidnon');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('12', 'Camiguin');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('12', 'Lanao del Norte');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('12', 'Misamis Occidental');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('12', 'Misamis Oriental');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('13', 'Davao de Oro');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('13', 'Davao del Norte');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('13', 'Davao del Sur');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('13', 'Davao Occidental');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('13', 'Davao Oriental');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('14', 'Cotabato');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('14', 'Sarangani');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('14', 'South Cotabato');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('14', 'Sultan Kudarat');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('15', 'Agusan del Norte');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('15', 'Agusan del Sur');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('15', 'Dinagat Islands');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('15', 'Surigao del Norte');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('15', 'Surigao del Sur');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('16', 'Abra');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('16', 'Apayao');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('16', 'Benguet');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('16', 'Ifugao');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('16', 'Kalinga');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('16', 'Mountain Province');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('17', 'Basilan');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('17', 'Lanao del Sur');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('17', 'Maguindanao');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('17', 'Sulu');
INSERT INTO `provinces` (`region_id`, `name`) VALUES ('17', 'Tawi-Tawi');